version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timout: 60
      runas: ubuntu
