spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mansa0805@gmail.com
    password: bqqqmwsslabjginy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  key: 43b7585079d42f271bc7c481ffca8f03