spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fingerorder_db
    username: root
    password: wpfkem!@34

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#                show_sql: true
        format_sql: true
  jwt:
    secret: ZmluZ2Vyb3JkZXItc3ByaW5nLWJvb3QtcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_NAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.springframework.web: trace
  #  org.hibernate.type: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : 5678

api:
  key: ${KAKAO_API_KEY}