spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: jwl970518+
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/practice
#    username: sa
#    password:


  #  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(CztzqxSLFEErm8ai3L/9PUolFtb1kEzKrwKoF0W+7zNvQnELroa54o00hppDiRuSqmPtgamn2npCWnYo0zmRNOvjZqMBGTP+TtP+u2DZ0YrJtyaNtGX2Pdn+q6tVgds3CaVi50VFtIw2kHZehnSmDg==)
#    username: ENC(Kyw5+LeCsi1ibPD+tQ4+Jq4o7uxvozoQ)
#    password: ENC(zUyRWn5EZnIuuRoFAdC69lESB/kXsuSD)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#                show_sql: true
        format_sql: true
  jwt:
    secret: ZmluZ2Vyb3JkZXItc3ByaW5nLWJvb3QtcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=
  mail:
    host: smtp.gmail.com
    port: 587
    username: mansa0805@gmail.com
    password: vhfyolvbnhijjqpn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.springframework.web: trace
#  org.apache: trace
  org.hibernate.type: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : 5678
