spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fingerorder_db
    username: root
    password: wpfkem!@34

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#                show_sql: true
        format_sql: true
  jwt:
    secret: ZmluZ2Vyb3JkZXItc3ByaW5nLWJvb3QtcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : 5678