spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(CztzqxSLFEErm8ai3L/9PUolFtb1kEzKrwKoF0W+7zNvQnELroa54o00hppDiRuSqmPtgamn2npCWnYo0zmRNOvjZqMBGTP+TtP+u2DZ0YrJtyaNtGX2Pdn+q6tVgds3CaVi50VFtIw2kHZehnSmDg==)
    username: ENC(Kyw5+LeCsi1ibPD+tQ4+Jq4o7uxvozoQ)
    password: ENC(zUyRWn5EZnIuuRoFAdC69lESB/kXsuSD)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #                show_sql: true
        format_sql: true

  jwt:
    secret: ZmluZ2Vyb3JkZXItc3ByaW5nLWJvb3QtcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_NAME}
    password: ${MAIL_USER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging.level:
  org.hibernate.SQL: debug
  #  org.springframework.web: trace
  #  org.hibernate.type: trace
#  org.apache: trace
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: 5678
api:
  key: ${API_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME}
